[package]
name = "espa"
version = "0.1.1"
authors = ["warlock <internalmike@gmail.com>"]
description = "A tool for converting ESM/ESP/ESS files to and from text format."
readme = "README.md"
keywords = ["esm", "esp", "ess", "mw", "yaml"]
categories = ["command-line-utilities", "encoding"]
license = "MIT/Apache-2.0"
repository = "https://github.com/A1-Triard/espa"
edition = "2018"

[dependencies]
esl = "0.0.6"
clap = "2.33.0"
encoding = "0.2.33"
serde_yaml = "0.8.11"
uuid = { version = "0.8.1", features = ["v4"] }
either = "1.5.3"
