name: esp-assembler
version: 0.12
synopsis: "A tool for converting ESM/ESP/ESS files to and from text format."
description: "A tool for converting ESM/ESP/ESS files to and from text format."
github: "A1-Triard/esp-assembler"
license: Apache
author: "Warlock <internalmike@gmail.com>"
maintainer: "Warlock <internalmike@gmail.com>"
copyright: "2016, 2017, 2018 Warlock <internalmike@gmail.com>"
category: CLI
#extra-source-files:

dependencies:
- base >= 4.11 && < 5
- MissingH
- base64-bytestring
- binary
- binary-ext
- bytestring
- conduit
- conduit-combinators
- conduit-extra
- containers
- data-binary-ieee754
- directory
- errors
- errors-ext
- monad-loops
- mono-traversable
- mtl
- semigroups
- split
- tes3
- text
- transformers
- utility-ht
- utf8-string
- zlib

default-extensions:
- BangPatterns
- CPP
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveGeneric
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- EmptyCase
- EmptyDataDecls
- ExistentialQuantification
- ExplicitForAll
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- LiberalTypeSynonyms
- MagicHash
- MonadComprehensions
- MultiParamTypeClasses
- MultiWayIf
- NegativeLiterals
- OverloadedStrings
- ParallelListComp
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TransformListComp
- TupleSections
- TypeFamilies
- TypeOperators
- UnboxedTuples
- UndecidableInstances
- UnicodeSyntax
- ViewPatterns

ghc-options:
- -fmax-pmcheck-iterations=100000000
- -O2
- -Wall
- -Werror
- -fno-warn-unused-imports
- -fprint-potential-instances
- -fsimpl-tick-factor=110

include-dirs:
- include

library:
  source-dirs: src

executables:
  espa:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - esp-assembler

tests:
  esp-assembler-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HUnit
    - esp-assembler
